export const types = {
    AUTH_LOADING: "AUTH_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    SIGNUP_ERROR: "SIGNUP_ERROR",

    DATA_LOADING: "DATA_LOADING",
    DATA_SUCCESS: "DATA_SUCCESS",
    DATA_ERROR: "DATA_ERROR",

}